#cloud-config
# Swiss Re Infrastructure - Version 2: Web Services
# Includes Version 1 + Apache with HTTPS

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  # Version 1 packages
  - ufw
  - fail2ban
  - unattended-upgrades
  - curl
  - wget
  - net-tools
  - htop
  - vim
  - git
  # Version 2 packages
  - apache2
  - libapache2-mod-security2
  - libapache2-mod-evasive
  - certbot
  - ssl-cert

write_files:
  # Version 1 configurations
  - path: /etc/ssh/sshd_config.d/hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication yes
      PubkeyAuthentication yes
      X11Forwarding no
      MaxAuthTries 3
      ClientAliveInterval 300
      ClientAliveCountMax 2
      AllowUsers swissreadmin
    permissions: '0644'

  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 5
      
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      
      [apache-auth]
      enabled = true
      port = http,https
      filter = apache-auth
      logpath = /var/log/apache2/error.log
    permissions: '0644'

  # Apache configuration
  - path: /etc/apache2/sites-available/swissre-ssl.conf
    content: |
      <VirtualHost *:443>
          ServerName swissre.local
          DocumentRoot /var/www/html
          
          SSLEngine on
          SSLCertificateFile /etc/ssl/certs/swissre.crt
          SSLCertificateKeyFile /etc/ssl/private/swissre.key
          
          SSLProtocol -all +TLSv1.2 +TLSv1.3
          SSLCipherSuite HIGH:!aNULL:!MD5:!3DES
          SSLHonorCipherOrder on
          
          Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
          Header always set X-Frame-Options "DENY"
          Header always set X-Content-Type-Options "nosniff"
          Header always set X-XSS-Protection "1; mode=block"
          Header always set Content-Security-Policy "default-src 'self'"
          
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
      
      <VirtualHost *:80>
          ServerName swissre.local
          Redirect permanent / https://swissre.local/
      </VirtualHost>
    permissions: '0644'

  # Self-signed certificate (temporary)
  - path: /tmp/generate-cert.sh
    content: |
      #!/bin/bash
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/ssl/private/swissre.key \
        -out /etc/ssl/certs/swissre.crt \
        -subj "/C=CH/ST=Zurich/L=Zurich/O=SwissRe/CN=swissre.local"
      chmod 600 /etc/ssl/private/swissre.key
      chmod 644 /etc/ssl/certs/swissre.crt
    permissions: '0755'

  # ModSecurity configuration
  - path: /etc/modsecurity/modsecurity.conf
    content: |
      SecRuleEngine On
      SecRequestBodyAccess On
      SecResponseBodyAccess Off
      SecRequestBodyLimit 13107200
      SecRequestBodyNoFilesLimit 131072
      SecRequestBodyLimitAction Reject
      SecAuditEngine On
      SecAuditLogParts ABCDEFGHIJKZ
      SecAuditLog /var/log/apache2/modsec_audit.log
    permissions: '0644'

  # Default web page
  - path: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Swiss Re Infrastructure Challenge</title>
          <style>
              body { font-family: Arial; text-align: center; padding: 50px; }
              .status { color: green; font-weight: bold; }
          </style>
      </head>
      <body>
          <h1>Swiss Re Infrastructure Challenge</h1>
          <h2>Version 2 - Web Services</h2>
          <p class="status">Apache HTTPS Server Active</p>
          <p>TLS 1.2+ Enforced | Security Headers Enabled</p>
      </body>
      </html>
    permissions: '0644'

runcmd:
  # Version 1 configurations
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow from 10.0.2.0/27 to any port 22 comment 'SSH from Bastion'
  
  # Version 2: Allow HTTP/HTTPS from firewall
  - ufw allow from 10.0.1.0/26 to any port 80 comment 'HTTP from Firewall'
  - ufw allow from 10.0.1.0/26 to any port 443 comment 'HTTPS from Firewall'
  - ufw --force enable
  
  # Generate self-signed certificate
  - bash /tmp/generate-cert.sh
  
  # Enable Apache modules
  - a2enmod ssl
  - a2enmod headers
  - a2enmod rewrite
  - a2enmod security2
  - a2enmod evasive
  
  # Enable site and disable default
  - a2dissite 000-default
  - a2ensite swissre-ssl
  
  # Start services
  - systemctl restart apache2
  - systemctl enable apache2
  - systemctl restart sshd
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Set timezone
  - timedatectl set-timezone UTC
  
  # Create health check script
  - |
    cat > /usr/local/bin/health-check.sh << 'EOF'
    #!/bin/bash
    echo "System Health Check - $(date)"
    echo "==================="
    echo "Hostname: $(hostname)"
    echo "Uptime: $(uptime)"
    echo "Memory: $(free -h | grep Mem)"
    echo "Disk: $(df -h | grep /dev/root)"
    echo "Network: $(ip -4 addr show | grep inet | grep -v 127.0.0.1)"
    echo "Firewall: $(ufw status | head -1)"
    echo "Apache: $(systemctl is-active apache2)"
    echo "HTTPS: $(netstat -tlpn | grep :443)"
    EOF
  - chmod +x /usr/local/bin/health-check.sh
  
  # Log deployment
  - echo "Version 2 deployment completed at $(date)" > /var/log/deployment.log

final_message: "Swiss Re Infrastructure Version 2 - Web Services Deployed"
