name: CD - Infrastructure Deployment
# Author: Jesus Gracia

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: echo 'Deployment started'